// constants.js

export const LANGUAGES = {
  en: { name: 'English', flag: '🇺🇸', code: 'en' },
  hi: { name: 'हिंदी', flag: '🇮🇳', code: 'hi' },
  mr: { name: 'मराठी', flag: '🇮🇳', code: 'mr' },
  ja: { name: '日本語', flag: '🇯🇵', code: 'ja' },
  es: { name: 'Español', flag: '🇪🇸', code: 'es' },
  fr: { name: 'Français', flag: '🇫🇷', code: 'fr' },
  de: { name: 'Deutsch', flag: '🇩🇪', code: 'de' }
};

export const TRANSLATIONS = {
  en: {
    makeMyComic: 'MAKE MY COMIC!',
    creating: 'CREATING...',
    searchPlaceholder: 'Enter a topic to create a comic about...',
    brainPowerLevel: 'BRAIN POWER LEVEL',
    elementary: 'ELEMENTARY',
    highSchool: 'HIGH SCHOOL',
    college: 'COLLEGE',
    points: 'POINTS',
    level: 'LEVEL',
    selectStyle: 'Select Your Style',
    learnInStyle: 'WIKICOMICS - LEARN IN STYLE!',
    createYourComic: 'CREATE YOUR COMIC!',
    selectYourStyle: 'SELECT YOUR STYLE!',
    previousQuests: 'YOUR PREVIOUS QUESTS:',
    unlockAtLevel: 'UNLOCK AT LVL',
    errorGenerating: 'Error generating comic',
    failedToSearch: 'Failed to search Wikipedia'
  },
  hi: {
    makeMyComic: 'मेरा कॉमिक बनाएं!',
    creating: 'बना रहे हैं...',
    searchPlaceholder: 'कॉमिक बनाने के लिए विषय दर्ज करें...',
    brainPowerLevel: 'बुद्धि स्तर',
    elementary: 'प्राथमिक',
    highSchool: 'माध्यमिक',
    college: 'महाविद्यालय',
    points: 'अंक',
    level: 'स्तर',
    selectStyle: 'अपनी शैली चुनें',
    learnInStyle: 'विकिकॉमिक्स - स्टाइल से सीखें!',
    createYourComic: 'अपना कॉमिक बनाएं!',
    selectYourStyle: 'अपनी शैली चुनें!',
    previousQuests: 'आपकी पिछली खोजें:',
    unlockAtLevel: 'स्तर पर अनलॉक करें',
    errorGenerating: 'कॉमिक बनाने में त्रुटि',
    failedToSearch: 'विकिपीडिया खोज विफल'
  },
  mr: {
    makeMyComic: 'माझे कॉमिक बनवा!',
    creating: 'तयार करत आहे...',
    searchPlaceholder: 'कॉमिक बनवण्यासाठी विषय टाका...',
    brainPowerLevel: 'बुद्धिमत्ता पातळी',
    elementary: 'प्राथमिक',
    highSchool: 'माध्यमिक',
    college: 'महाविद्यालय',
    points: 'गुण',
    level: 'पातळी',
    selectStyle: 'तुमची शैली निवडा',
    learnInStyle: 'विकिकॉमिक्स - स्टाईलने शिका!',
    createYourComic: 'तुमचे कॉमिक बनवा!',
    selectYourStyle: 'तुमची शैली निवडा!',
    previousQuests: 'तुमच्या मागील शोध:',
    unlockAtLevel: 'पातळीवर अनलॉक करा',
    errorGenerating: 'कॉमिक बनवताना त्रुटी',
    failedToSearch: 'विकिपीडिया शोध अयशस्वी'
  },
  ja: {
    makeMyComic: 'コミックを作成！',
    creating: '作成中...',
    searchPlaceholder: 'コミックのテーマを入力してください...',
    brainPowerLevel: '知力レベル',
    elementary: '小学校',
    highSchool: '高校',
    college: '大学',
    points: 'ポイント',
    level: 'レベル',
    selectStyle: 'スタイルを選択',
    learnInStyle: 'ウィキコミックス - スタイリッシュに学ぼう！',
    createYourComic: 'コミックを作成！',
    selectYourStyle: 'スタイルを選択！',
    previousQuests: '過去の検索：',
    unlockAtLevel: 'レベルでアンロック',
    errorGenerating: 'コミック生成エラー',
    failedToSearch: 'ウィキペディア検索に失敗'
  },
  es: {
    makeMyComic: '¡CREAR MI CÓMIC!',
    creating: 'CREANDO...',
    searchPlaceholder: 'Ingresa un tema para crear un cómic...',
    brainPowerLevel: 'NIVEL DE PODER CEREBRAL',
    elementary: 'PRIMARIA',
    highSchool: 'SECUNDARIA',
    college: 'UNIVERSIDAD',
    points: 'PUNTOS',
    level: 'NIVEL',
    selectStyle: 'Selecciona Tu Estilo',
    learnInStyle: '¡WIKICOMICS - APRENDE CON ESTILO!',
    createYourComic: '¡CREA TU CÓMIC!',
    selectYourStyle: '¡SELECCIONA TU ESTILO!',
    previousQuests: 'TUS BÚSQUEDAS ANTERIORES:',
    unlockAtLevel: 'DESBLOQUEAR EN NIVEL',
    errorGenerating: 'Error al generar el cómic',
    failedToSearch: 'Error al buscar en Wikipedia'
  },
  fr: {
    makeMyComic: 'CRÉER MA BD !',
    creating: 'CRÉATION...',
    searchPlaceholder: 'Entrez un sujet pour créer une BD...',
    brainPowerLevel: 'NIVEAU DE PUISSANCE CÉRÉBRALE',
    elementary: 'ÉLÉMENTAIRE',
    highSchool: 'LYCÉE',
    college: 'UNIVERSITÉ',
    points: 'POINTS',
    level: 'NIVEAU',
    selectStyle: 'Sélectionnez Votre Style',
    learnInStyle: 'WIKICOMICS - APPRENEZ AVEC STYLE !',
    createYourComic: 'CRÉEZ VOTRE BD !',
    selectYourStyle: 'SÉLECTIONNEZ VOTRE STYLE !',
    previousQuests: 'VOS RECHERCHES PRÉCÉDENTES :',
    unlockAtLevel: 'DÉBLOQUER AU NIVEAU',
    errorGenerating: 'Erreur lors de la génération de la BD',
    failedToSearch: 'Échec de la recherche Wikipedia'
  },
  de: {
    makeMyComic: 'ERSTELLE MEINEN COMIC!',
    creating: 'ERSTELLEN...',
    searchPlaceholder: 'Gib ein Thema für deinen Comic ein...',
    brainPowerLevel: 'GEHIRNLEISTUNG',
    elementary: 'GRUNDSCHULE',
    highSchool: 'GYMNASIUM',
    college: 'UNIVERSITÄT',
    points: 'PUNKTE',
    level: 'LEVEL',
    selectStyle: 'Wähle Deinen Stil',
    learnInStyle: 'WIKICOMICS - LERNE MIT STIL!',
    createYourComic: 'ERSTELLE DEINEN COMIC!',
    selectYourStyle: 'WÄHLE DEINEN STIL!',
    previousQuests: 'DEINE VORHERIGEN SUCHEN:',
    unlockAtLevel: 'FREISCHALTEN AUF LEVEL',
    errorGenerating: 'Fehler beim Generieren des Comics',
    failedToSearch: 'Wikipedia-Suche fehlgeschlagen'
  }
}; 